services:
  db:
    image: database
    container_name: database
    build:
      dockerfile: ./config/database/Dockerfile
    env_file:
      - ./config/database/.env
    ports:
      - "8306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_network
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10

  backend:
    image: backend
    container_name: backend
    build:
      dockerfile: ./config/backend/Dockerfile
    ports:
      - "8001:8000"
      - "9229:9229" # Debug
    volumes:
      - ./backend:/backend
    command: /entrypoint.sh
    networks:
      - db_network
    depends_on:
      db:
        condition: service_healthy
        restart: true

  frontend:
    image: frontend
    container_name: frontend
    build:
      dockerfile: ./config/frontend/Dockerfile
    ports:
      - "8000:3000"
    volumes:
      - ./frontend:/frontend
    command: /entrypoint.sh
    depends_on:
      - backend

networks:
    db_network:
        driver: bridge

volumes:
    db_data:
      name: mysql-volume