services:
  db:
    image: database
    container_name: database
    build:
      dockerfile: ./config/database/Dockerfile
    env_file:
      - ./config/database/.env
    ports:
      - "8306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_network
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10

  script_bootstrap_db:
    image : script_bootstrap_db
    container_name: script_bootstrap_db
    build:
      dockerfile: ./config/script_bootstrap_db/Dockerfile
    env_file:
      - ./config/script_bootstrap_db/.env
    volumes:
      - script_profile_pictures:/backend/src/uploads
    command: /entrypoint.sh
    networks:
      - db_network
    depends_on:
      db:
        condition: service_healthy
      

  backend:
    image: backend
    container_name: backend
    build:
      dockerfile: ./config/backend/Dockerfile
    ports:
      - "8001:8000"
      - "9229:9229" # Debug
    env_file:
      - ./config/backend/.env
    volumes:
      - ./backend:/backend
      - script_profile_pictures:/backend/src/uploads
    command: /entrypoint.sh
    networks:
      - db_network
    depends_on:
      script_bootstrap_db:
        condition: service_completed_successfully

  frontend:
    image: frontend
    container_name: frontend
    build:
      dockerfile: ./config/frontend/Dockerfile
    ports:
      - "8000:3000"
    env_file:
      - ./config/frontend/.env
    volumes:
      - ./frontend:/frontend  
    command: /entrypoint.sh
    depends_on:
      script_bootstrap_db:
        condition: service_completed_successfully


networks:
    db_network:
        driver: bridge

volumes:
    db_data:
      name: mysql-volume
    script_profile_pictures: {} 